name: CI – Full Stack Project
on:
  push:
      branches: [main]
  pull_request:
      branches: [main]

jobs:
    # FRONTEND CHECKS
  frontend:
    name: Frontend – Lint & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Build app
        run: npm run build

  # BACKEND CHECKS
  backend:
    name: Backend – Lint & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint backend
        run: npm run lint

      - name: Run backend tests
        run: npm test

  # AI SCRIPT CHECKS
  ai:
    name: AI – Python Linting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ai
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check syntax (Python)
        run: python -m compileall .